steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/qbitkit-notebook:latest','-f','Dockerfile.jupyter_notebook','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/qbitkit-docs-static:latest','-f','doc/sphinx/Dockerfile.for_building_docs','./doc/sphinx/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/qbitkit-build-then-host-docs:latest','-f','doc/sphinx/Dockerfile.build_then_host','./doc/sphinx/']
timeout: 300s
options:
  machine_type: 'N1_HIGHCPU_8'
images:
  - 'us.gcr.io/$PROJECT_ID/qbitkit-notebook:latest'
  - 'us.gcr.io/$PROJECT_ID/qbitkit-docs-static:latest'
  - 'us.gcr.io/$PROJECT_ID/qbitkit-build-then-host-docs:latest'