steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
    entrypoint: 'bash'
    args: ['./.gcs_upload_hook.sh', $_DOC_FORMAT, $_GCS_LOCATION]
timeout: 1800s
options:
  machine_type: 'N1_HIGHCPU_8'