steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t',
           'gcr.io/$PROJECT_ID/qbitkit-notebook:latest',
           '-f',
           '../Dockerfile',
           '..']
timeout: 300s
options:
  machine_type: 'N1_HIGHCPU_32'
images:
  - 'us.gcr.io/$PROJECT_ID/qbitkit-notebook:latest'